#!/usr/bin/env python3
"""
pinwheel_round2.py -- Topic 34 (B1), ROUND 2 experiments for the JNCA manuscript.

Purely additive on top of `pinwheel_sim.py` (round 1, kept byte-identical; a copy of the
round-1 file is pinwheel_sim.bak_20260905_round1.py).  Round-1 results E1/E2/E3 are
regenerated by `python pinwheel_sim.py --exp all`; this module adds:

  E1b  admission conservatism: fraction of *schedulable* profiles that the O(1) density test
       (Cor. 2) refuses, per density bin.  Derived from results/E1_density_sweep.json.
  E4   fleet dimensioning over the whole 121-camera corpus: number of edge boxes needed by
       (a) harmonic rounding + FFD into unit-density boxes (Cor. 3, provable factor 2),
       (b) FFD into 5/6-capacity boxes (heuristic -- no bound is claimed for it),
       (c) EDF-fit (open a new box when lazy EDF violates), sweeping K_target.
  E5   admission control under churn: cameras join/leave (Poisson), density admission
       (Cor. 2, thresholds 5/6 and 1 with harmonic rounding) vs admit-then-EDF.
  E6   VLM escalation blackouts (Prop. 3): l in {2,4,8}, P_e in {50,100,200}.
  E7   energy in absolute mJ + consolidation gain, for every E2 configuration.
       E_idle = 30.4 mJ, E_active = 290.8 mJ per slot -- REUSED from the companion paper
       (Deep3, Table I; Jetson Orin Nano). Declared reuse, no new measurement.
  E8   sensitivity: (i) shaping windows fitted on the first half of each camera's history and
       replayed on the second half (no oracle); (ii) per-dataset split CDnet2014/LASIESTA/BMC;
       (iii) a certified-latency cap K_max on the shaping grid.

Usage:  python pinwheel_round2.py --exp E1b|E4|E5|E6|E7|E8|figs|all [--quick]
Seed 42 throughout.  Outputs results/E4_*.json ... results/E8_*.json + figures.
"""
import argparse, json, math, os, random, sys, time
from collections import defaultdict

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from pinwheel_sim import (RESULTS, SEED, load_corpus, density, edf_schedule, harmonic_round,
                          harmonic_schedule, max_gaps, replay, shaped_windows,
                          shaped_harmonic_windows, shaping_objective, build_streams)

# Energy anchors -- companion paper (Deep3) Table I, Jetson Orin Nano. Reused, not re-measured.
E_IDLE_MJ = 30.4
E_ACTIVE_MJ = 290.8


def energy_per_slot(a):
    """Linear slot-energy model of the companion paper: E(a) = E_idle + a (E_active - E_idle)."""
    return E_IDLE_MJ + a * (E_ACTIVE_MJ - E_IDLE_MJ)


def pow2_floor(k):
    return 1 << int(math.floor(math.log2(k)))


def ffd(items, cap):
    """First-Fit-Decreasing. Returns (bins as index lists, loads)."""
    order = sorted(range(len(items)), key=lambda i: -items[i])
    bins, load = [], []
    for i in order:
        for b in range(len(bins)):
            if load[b] + items[i] <= cap + 1e-12:
                bins[b].append(i)
                load[b] += items[i]
                break
        else:
            bins.append([i])
            load.append(items[i])
    return bins, load


def rr_schedule(K, H):
    """Proportional-share round robin over the N cameras (baseline #2, answer to R2-6):
    serve cameras cyclically, one slot each, ignoring the windows."""
    N = len(K)
    return np.array([t % N for t in range(H)], dtype=np.int32)


# --------------------------------------------------------------------------- corpus helpers
def all_streams(videos, nframes, events, H, order=None):
    """One camera per video (121 of them), each wrapped cyclically to H slots."""
    out = []
    for v in (order or videos):
        n = nframes[v]
        ev, m = [], 0
        while m * n < H:
            for (s, d) in events[v]:
                s2 = s + m * n
                if s2 + d - 1 < H:
                    ev.append((s2, d))
            m += 1
        out.append({"video": f"{v[0]}/{v[1]}", "dataset": v[0], "n_frames": n, "events": ev,
                    "raw_events": events[v]})
    return out


def split_streams(videos, nframes, events, H, half="train"):
    """Holdout split: events whose onset lies in the first / second half of the source video."""
    out = []
    for v in videos:
        n = nframes[v]
        mid = n // 2
        if half == "train":
            base = [(s, d) for (s, d) in events[v] if s < mid]
            span = mid
        else:
            base = [(s - mid, d) for (s, d) in events[v] if s >= mid]
            span = n - mid
        span = max(1, span)
        ev, m = [], 0
        while m * span < H:
            for (s, d) in base:
                s2 = s + m * span
                if s2 + d - 1 < H:
                    ev.append((s2, d))
            m += 1
        out.append({"video": f"{v[0]}/{v[1]}", "dataset": v[0], "n_frames": span,
                    "events": ev, "raw_events": base})
    return out


# --------------------------------------------------------------------------- E1b
def run_E1b():
    """Admission conservatism of the O(1) density rule (answer to R2-11)."""
    p = os.path.join(RESULTS, "E1_density_sweep.json")
    d = json.load(open(p))
    rows = d["instances"]
    bins = defaultdict(list)
    for r in rows:
        bins[r["bin"]].append(r)
    out = []
    for b, R in bins.items():
        dec = [r for r in R if r["exact"] is not None]
        sched = [r for r in dec if r["exact"]]
        refused = [r for r in sched if r["rho"] > 5 / 6 + 1e-12]
        out.append({"bin": b, "n_decided": len(dec), "n_schedulable": len(sched),
                    "n_refused_by_5_6": len(refused),
                    "conservatism": len(refused) / len(sched) if sched else None,
                    "unschedulable_below_5_6": sum(1 for r in dec
                                                   if (not r["exact"]) and r["rho"] <= 5 / 6)})
    tot_sched = sum(o["n_schedulable"] for o in out)
    tot_ref = sum(o["n_refused_by_5_6"] for o in out)
    res = {"meta": {"source": "results/E1_density_sweep.json",
                    "definition": "conservatism = P(density test refuses | instance is schedulable)"},
           "bins": sorted(out, key=lambda o: o["bin"]),
           "overall": {"n_schedulable": tot_sched, "n_refused": tot_ref,
                       "conservatism": tot_ref / tot_sched if tot_sched else None,
                       "unschedulable_below_5_6_total":
                           sum(o["unschedulable_below_5_6"] for o in out)}}
    json.dump(res, open(os.path.join(RESULTS, "E1b_admission_conservatism.json"), "w"), indent=1)
    return res


# --------------------------------------------------------------------------- E4
def profile_from_trace(streams, K_target, Kmin=2, Kmax=64):
    """Heterogeneous certificate profile anchored on the trace: a camera whose events are
    shorter than the corpus median gets a proportionally shorter window."""
    med = []
    for st in streams:
        d = [dd for (_, dd) in st["raw_events"]]
        med.append(float(np.median(d)) if d else 1.0)
    ref = float(np.median(med))
    K = []
    for m in med:
        k = int(round(K_target * m / max(1e-9, ref)))
        K.append(int(min(Kmax, max(Kmin, k))))
    return K


def box_violations(Ksub, streams_sub, H, scheduler):
    """Run one box and count certificate violations + missed certified events."""
    if scheduler == "harmonic":
        sched, _ = harmonic_schedule(Ksub, H)
        if sched is None:
            return None
    elif scheduler == "edf":
        sched = edf_schedule(Ksub, H, lazy=True)
    else:
        raise ValueError(scheduler)
    warm = max(Ksub)
    gaps = max_gaps(sched, len(Ksub), H, warm)
    viol = sum(1 for i, g in enumerate(gaps) if g > Ksub[i])
    rp = replay(sched, streams_sub, Ksub, warm)
    busy = float(np.mean(sched[warm:] >= 0))
    return {"violating_cameras": viol, "miss_cert": rp["miss_cert"], "n_cert": rp["n_cert"],
            "n_events": rp["n_events"], "miss_all": rp["miss_all"], "busy": busy,
            "rho": density(Ksub)}


def run_E4(quick, videos, nframes, events):
    H = 3000 if quick else 6000
    Ktargets = [8, 12, 16, 24]
    streams = all_streams(videos, nframes, events, H)
    M = len(streams)
    rows = []
    for Kt in Ktargets:
        for pname in ("uniform", "trace_heterogeneous"):
            K = [Kt] * M if pname == "uniform" else profile_from_trace(streams, Kt)
            rho = density(K)
            # ---- (a) Cor. 3: harmonic rounding + FFD into unit-density boxes -------------
            Khat = [pow2_floor(k) for k in K]
            bins_h, load_h = ffd([1.0 / k for k in Khat], 1.0)
            res_h = [box_violations([Khat[i] for i in b], [streams[i] for i in b], H, "harmonic")
                     for b in bins_h]
            # ---- (b) heuristic: FFD into 5/6-capacity boxes on the *original* windows ----
            bins_f, load_f = ffd([1.0 / k for k in K], 5 / 6)
            res_f, constructible = [], 0
            for b in bins_f:
                r = box_violations([K[i] for i in b], [streams[i] for i in b], H, "harmonic")
                if r is None:
                    r = box_violations([K[i] for i in b], [streams[i] for i in b], H, "edf")
                    r["constructive"] = False
                else:
                    r["constructive"] = True
                    constructible += 1
                res_f.append(r)
            # ---- (c) EDF-fit: greedily grow a box while lazy EDF shows no violation ------
            bins_e, cur = [], []
            for i in sorted(range(M), key=lambda i: K[i]):
                trial = cur + [i]
                sched = edf_schedule([K[j] for j in trial], H, lazy=True)
                g = max_gaps(sched, len(trial), H, max(K[j] for j in trial))
                if all(g[t] <= K[j] for t, j in enumerate(trial)):
                    cur = trial
                else:
                    bins_e.append(cur)
                    cur = [i]
            if cur:
                bins_e.append(cur)
            res_e = [box_violations([K[i] for i in b], [streams[i] for i in b], H, "edf")
                     for b in bins_e]

            def agg(res, bins, tag, boxes_pred=None):
                return {"method": tag, "boxes": len(bins),
                        "boxes_predicted": boxes_pred,
                        "violating_cameras": int(sum(r["violating_cameras"] for r in res)),
                        "miss_cert": int(sum(r["miss_cert"] for r in res)),
                        "n_cert": int(sum(r["n_cert"] for r in res)),
                        "n_events": int(sum(r["n_events"] for r in res)),
                        "busy_mean": float(np.mean([r["busy"] for r in res])),
                        "rho_max": float(max(r["rho"] for r in res))}

            a_ = agg(res_h, bins_h, "cor3_harmonic_ffd",
                     math.ceil(sum(1.0 / k for k in Khat) - 1e-12))
            a_["constructive_boxes"] = len(bins_h)
            b_ = agg(res_f, bins_f, "ffd_5_6_heuristic")
            b_["constructive_boxes"] = constructible
            c_ = agg(res_e, bins_e, "edf_fit_heuristic")
            c_["constructive_boxes"] = 0
            lb = math.ceil(rho - 1e-12)
            for a in (a_, b_, c_):
                a.update({"K_target": Kt, "profile": pname, "M_cameras": M, "rho": rho,
                          "lower_bound_boxes": lb, "boxes_over_lb": a["boxes"] / lb,
                          "cor3_bound_ceil_2rho": math.ceil(2 * rho - 1e-12)})
                rows.append(a)
    out = {"meta": {"seed": SEED, "H": H, "K_targets": Ktargets, "M_cameras": M,
                    "profiles": {"uniform": "K_i = K_target for all 121 cameras",
                                 "trace_heterogeneous":
                                     "K_i = round(K_target * median duration_i / corpus median), clipped to [2,64]"},
                    "methods": {"cor3_harmonic_ffd":
                                "K_i -> 2^floor(log2 K_i), FFD into capacity-1 boxes, constructive harmonic scheduler (Cor. 3; provable m <= ceil(2 rho))",
                                "ffd_5_6_heuristic":
                                "FFD of 1/K_i into capacity-5/6 boxes; schedulable by Thm 1(ii) but our constructive scheduler may fail -> EDF fallback. NO bound is claimed.",
                                "edf_fit_heuristic":
                                "open a new box whenever lazy EDF violates a window"}},
           "rows": rows}
    json.dump(out, open(os.path.join(RESULTS, "E4_fleet_dimensioning.json"), "w"), indent=1)
    return out


# --------------------------------------------------------------------------- E5
def run_E5(quick, videos, nframes, events):
    """One edge box, cameras join/leave. Density admission (Cor. 2) vs admit-then-EDF."""
    H = 4000 if quick else 8000
    reps = 4 if quick else 10
    lam_levels = [(0.004, 0.004), (0.010, 0.006), (0.020, 0.006),
                  (0.040, 0.006), (0.080, 0.006)]                   # (join rate, leave rate)
    Kgrid = [4, 6, 8, 12, 16, 24, 32]
    policies = ["density_5_6", "density_1_harmonic", "admit_then_edf",
                "harmonic_residue_constructive"]
    M_RES = 64          # residue wheel: every rounded window divides it (K_grid max is 32)
    rows = []
    for (lin, lout) in lam_levels:
        for pol in policies:
            for rep in range(reps):
                rng = random.Random(SEED * 7919 + rep * 31 + int(lin * 1e5) + hash(pol) % 997)
                active = []          # list of dicts: idx, K, stream
                n_req = n_rej = 0
                viol_slots = 0
                busy_slots = 0
                served_since = {}
                cam_uid = 0
                occupied = [False] * M_RES        # residue wheel for the constructive policy
                for t in range(H):
                    # --- arrivals ---
                    if rng.random() < lin:
                        n_req += 1
                        v = rng.choice(videos)
                        Knew = rng.choice(Kgrid)
                        cand = [c["K"] for c in active] + [Knew]
                        res = None
                        if pol == "density_5_6":
                            ok = density(cand) <= 5 / 6 + 1e-12
                        elif pol == "density_1_harmonic":
                            ok = sum(1.0 / pow2_floor(k) for k in cand) <= 1.0 + 1e-12
                        elif pol == "harmonic_residue_constructive":
                            kh = pow2_floor(Knew)
                            for r in range(kh):
                                if not any(occupied[x] for x in range(r, M_RES, kh)):
                                    res = r
                                    break
                            ok = res is not None
                        else:
                            ok = density(cand) <= 1.0 + 1e-12
                        if ok:
                            if res is not None:
                                kh = pow2_floor(Knew)
                                for x in range(res, M_RES, kh):
                                    occupied[x] = True
                            active.append({"uid": cam_uid, "K": Knew, "v": v,
                                           "khat": pow2_floor(Knew), "res": res, "t0": t})
                            served_since[cam_uid] = t
                            cam_uid += 1
                        else:
                            n_rej += 1
                    # --- departures ---
                    if active and rng.random() < lout * len(active):
                        c = active.pop(rng.randrange(len(active)))
                        served_since.pop(c["uid"], None)
                        if c["res"] is not None:
                            for x in range(c["res"], M_RES, c["khat"]):
                                occupied[x] = False
                    if not active:
                        continue
                    # --- one slot of service ---
                    if pol == "harmonic_residue_constructive":
                        # fixed residue wheel: camera i is served at every slot t = res_i (mod khat_i).
                        # Offsets of admitted cameras are never reassigned, so a join or a leave
                        # cannot stretch anybody else's gap.
                        for c in active:
                            if t % c["khat"] == c["res"] % c["khat"]:
                                served_since[c["uid"]] = t
                                busy_slots += 1
                                break
                    else:
                        Keff = ([pow2_floor(c["K"]) for c in active]
                                if pol == "density_1_harmonic" else [c["K"] for c in active])
                        dl = [served_since[c["uid"]] + Keff[j] for j, c in enumerate(active)]
                        j = min(range(len(active)), key=lambda j: (dl[j], -Keff[j]))
                        must = any(sorted(dl)[k] <= t + k for k in range(len(active)))
                        if must:
                            served_since[active[j]["uid"]] = t
                            busy_slots += 1
                    # --- violations: a camera whose window has elapsed without service ---
                    for c in active:
                        if t - served_since[c["uid"]] > c["K"]:
                            viol_slots += 1
                            served_since[c["uid"]] = t     # reset so we count episodes, not slots
                rows.append({"lambda_in": lin, "lambda_out": lout, "policy": pol, "rep": rep,
                             "requests": n_req, "rejections": n_rej,
                             "rejection_rate": n_rej / max(1, n_req),
                             "violation_episodes": viol_slots,
                             "violations_per_1k_slots": 1000.0 * viol_slots / H,
                             "busy_fraction": busy_slots / H,
                             "final_active": len(active)})
    agg = defaultdict(list)
    for r in rows:
        agg[(r["lambda_in"], r["lambda_out"], r["policy"])].append(r)
    summary = [{"lambda_in": k[0], "lambda_out": k[1], "policy": k[2], "n": len(R),
                "rejection_rate": float(np.mean([r["rejection_rate"] for r in R])),
                "violations_per_1k_slots": float(np.mean([r["violations_per_1k_slots"] for r in R])),
                "violation_episodes_total": int(sum(r["violation_episodes"] for r in R)),
                "busy_fraction": float(np.mean([r["busy_fraction"] for r in R])),
                "mean_active": float(np.mean([r["final_active"] for r in R]))}
               for k, R in sorted(agg.items())]
    out = {"meta": {"seed": SEED, "H": H, "reps": reps, "K_grid": Kgrid,
                    "churn": "join ~ Bernoulli(lambda_in) per slot; leave ~ Bernoulli(lambda_out * n_active) per slot",
                    "policies": {"density_5_6": "admit iff rho + 1/K_new <= 5/6 (Cor. 2)",
                                 "density_1_harmonic": "round K down to a power of two, admit iff rounded density <= 1 (Prop. 1a + Cor. 2)",
                                 "admit_then_edf": "admit while rho <= 1, rely on lazy EDF",
                                 "harmonic_residue_constructive": "admit iff a free residue class exists on a 64-slot dyadic wheel (equivalent to the harmonic density test, but it also *constructs* the schedule); offsets of admitted cameras are never reassigned"},
                    "note": "a violation episode = a camera whose window elapsed without service; the counter is reset after each episode so that one long outage is not counted many times"},
           "summary": summary, "runs": rows}
    json.dump(out, open(os.path.join(RESULTS, "E5_churn_admission.json"), "w"), indent=1)
    return out


# --------------------------------------------------------------------------- E6
def blackout_mask(H, l, Pe, rng, mode="periodic"):
    m = np.zeros(H, dtype=bool)
    t = rng.randrange(Pe)
    while t < H:
        m[t:min(t + l, H)] = True
        t += Pe if mode == "periodic" else Pe + rng.randrange(0, Pe)
    return m


def prop3_budget(K, l, Pe):
    """Provable blackout budget (A3.7): at most ceil((K+l-1)/P_e) escalations intersect a
    window of K slots, each costing at most l slots."""
    return min(K, l * int(math.ceil((K + l - 1) / Pe)))


def run_E6(quick, videos, nframes, events):
    H = 4000 if quick else 8000
    seeds = 4 if quick else 8
    N = 6
    Ks = [8, 10, 12, 14, 16, 20, 24, 32]
    ls = [2, 4, 8]
    Pes = [50, 100, 200]
    rows = []
    for K0 in Ks:
        K = [K0] * N
        for l in ls:
            for Pe in Pes:
                B = prop3_budget(K0, l, Pe)
                Kpp = K0 - B
                feasible = (Kpp > 0) and (sum(1.0 / Kpp for _ in range(N)) <= 5 / 6 + 1e-12)
                feasible_exact = (Kpp >= N)      # homogeneous: round robin on available slots
                for mode in ("periodic", "jittered"):
                    for sd in range(seeds):
                        rng = random.Random(SEED * 1000 + sd * 17 + l * 3 + Pe)
                        streams = build_streams(rng, videos, nframes, events, N, H)
                        mask = blackout_mask(H, l, Pe, rng, mode)
                        avail = np.flatnonzero(~mask)
                        sched = np.full(H, -1, dtype=np.int32)
                        # round robin over the AVAILABLE-slot subsequence (Prop. 3 construction)
                        for idx, t in enumerate(avail):
                            sched[t] = idx % N
                        warm = 2 * K0
                        gaps = max_gaps(sched, N, H, warm)
                        viol = sum(1 for i, g in enumerate(gaps) if g > K[i])
                        rp = replay(sched, streams, K, warm)
                        rows.append({"K": K0, "l": l, "Pe": Pe, "mode": mode, "seed": sd,
                                     "budget_B": B, "K_avail": Kpp,
                                     "prop3_feasible_5_6": bool(feasible),
                                     "prop3_feasible_exact": bool(feasible_exact),
                                     "violating_cameras": viol, "max_gap": int(max(gaps)),
                                     "miss_cert": rp["miss_cert"], "n_cert": rp["n_cert"],
                                     "blackout_fraction": float(mask.mean())})
    agg = defaultdict(list)
    for r in rows:
        agg[(r["K"], r["l"], r["Pe"], r["mode"])].append(r)
    summary = [{"K": k[0], "l": k[1], "Pe": k[2], "mode": k[3], "n": len(R),
                "budget_B": R[0]["budget_B"], "K_avail": R[0]["K_avail"],
                "prop3_feasible_5_6": R[0]["prop3_feasible_5_6"],
                "prop3_feasible_exact": R[0]["prop3_feasible_exact"],
                "violating_runs": int(sum(1 for r in R if r["violating_cameras"] > 0)),
                "miss_cert_total": int(sum(r["miss_cert"] for r in R)),
                "n_cert_total": int(sum(r["n_cert"] for r in R)),
                "blackout_fraction": float(np.mean([r["blackout_fraction"] for r in R]))}
               for k, R in sorted(agg.items())]
    pred_ok = sum(1 for s in summary
                  if (s["prop3_feasible_exact"] and s["violating_runs"] == 0)
                  or ((not s["prop3_feasible_exact"]) and s["violating_runs"] > 0))
    out = {"meta": {"seed": SEED, "H": H, "N": N, "Ks": Ks, "l": ls, "Pe": Pes,
                    "budget": "B = min(K, l*ceil((K+l-1)/P_e)) -- provable form, see A3.7",
                    "scheduler": "round robin over the available-slot subsequence (online, needs no forecast of escalations)",
                    "modes": {"periodic": "escalations exactly every P_e slots (tightest)",
                              "jittered": "gaps drawn uniformly in [P_e, 2 P_e)"}},
           "prediction_cells_correct": pred_ok, "prediction_cells": len(summary),
           "summary": summary, "runs": rows}
    json.dump(out, open(os.path.join(RESULTS, "E6_blackout.json"), "w"), indent=1)
    return out


# --------------------------------------------------------------------------- E7
def run_E7():
    """Absolute mJ and consolidation gain for every E2 configuration."""
    d = json.load(open(os.path.join(RESULTS, "E2_trace_frontier.json")))
    rows = []
    for s in d["summary"]:
        if s["scheduler"] != "harmonic":
            continue
        N, rho = s["N"], s["rho_mean"]
        busy = s["busy_mean"]
        shared = energy_per_slot(busy)                    # one shared accelerator
        # N private accelerators, camera i duty cycle 1/K_i; with the realised mean density
        # rho = sum 1/K_i the total private duty is the same rho spread over N devices
        private = N * E_IDLE_MJ + rho * (E_ACTIVE_MJ - E_IDLE_MJ)
        rows.append({"N": N, "rho_star": s["rho_star"], "profile": s["profile"],
                     "rho": rho, "busy": busy,
                     "mJ_per_slot_shared": shared,
                     "mJ_per_slot_private_fleet": private,
                     "mJ_per_camera_frame_shared": shared / N,
                     "mJ_per_camera_frame_private": private / N,
                     "consolidation_gain": private / shared,
                     "idle_mJ_saved_per_slot": private - shared,
                     "miss_all_rate": s["miss_all_rate_mean"]})
    out = {"meta": {"E_idle_mJ": E_IDLE_MJ, "E_active_mJ": E_ACTIVE_MJ,
                    "source": "companion paper (Deep3) Table I, Jetson Orin Nano -- REUSED, declared, not re-measured",
                    "model": "E(a) = E_idle + a (E_active - E_idle) per slot",
                    "private_fleet": "N accelerators, each idling at E_idle, total active duty = rho",
                    "consolidation_gain": "private / shared energy per slot"},
           "rows": rows,
           "gain_min": min(r["consolidation_gain"] for r in rows),
           "gain_max": max(r["consolidation_gain"] for r in rows)}
    json.dump(out, open(os.path.join(RESULTS, "E7_energy_mJ.json"), "w"), indent=1)
    return out


# --------------------------------------------------------------------------- E8
def eval_profile(streams, K, H, scheduler="harmonic"):
    if scheduler == "harmonic":
        sched, _ = harmonic_schedule(K, H)
        if sched is None:
            return None
    elif scheduler == "rr":
        sched = rr_schedule(K, H)
    else:
        sched = edf_schedule(K, H, lazy=True)
    warm = max(K)
    gaps = max_gaps(sched, len(K), H, warm)
    rp = replay(sched, streams, K, warm)
    return {"miss_all_rate": rp["miss_all"] / max(1, rp["n_events"]),
            "miss_cert": rp["miss_cert"], "n_cert": rp["n_cert"], "n_events": rp["n_events"],
            "violating_cameras": sum(1 for i, g in enumerate(gaps) if g > K[i]),
            "busy": float(np.mean(sched[warm:] >= 0)), "rho": density(K),
            "lat_max_cert": rp["lat_max_cert"]}


def run_E8(quick, videos, nframes, events):
    H = 3000 if quick else 6000
    seeds = 6 if quick else 12
    Ns = [6, 8, 12]
    budgets = [0.5, 2 / 3, 5 / 6, 1.0]
    out = {"meta": {"seed": SEED, "H": H, "seeds": seeds, "Ns": Ns, "budgets": budgets}}

    # ---- (i) HOLD-OUT: fit shaping windows on the first half, evaluate on the second -----
    # A temporal split needs at least one event in each half; only some videos qualify.
    eligible = [v for v in videos
                if any(e[0] < nframes[v] // 2 for e in events[v])
                and any(e[0] >= nframes[v] // 2 for e in events[v])]
    out["meta"]["holdout_eligible_videos"] = len(eligible)
    out["meta"]["holdout_total_videos"] = len(videos)
    rows = []
    for N in Ns:
        for rho_star in budgets:
            for sd in range(seeds):
                rng = random.Random(SEED * 1000 + sd)
                vs = rng.sample(eligible, N)
                tr = split_streams(vs, nframes, events, H, "train")
                te = split_streams(vs, nframes, events, H, "test")
                if min(len(s["raw_events"]) for s in tr) == 0 or \
                   min(len(s["raw_events"]) for s in te) == 0:
                    continue
                Ku = max(2, math.ceil(N / rho_star))
                K_uniform = [Ku] * N
                K_oracle = shaped_harmonic_windows(te, rho_star)[0]     # fitted on TEST (oracle)
                K_fit = shaped_harmonic_windows(tr, rho_star)[0]        # fitted on TRAIN
                r = {"N": N, "rho_star": rho_star, "seed": sd}
                for tag, K in (("uniform", K_uniform), ("shaped_oracle", K_oracle),
                               ("shaped_holdout", K_fit)):
                    e = eval_profile(te, K, H, "harmonic")
                    if e is None:
                        e = eval_profile(te, K, H, "edf")
                        e["constructive"] = False
                    else:
                        e["constructive"] = True
                    r[tag] = e
                    r[tag + "_K"] = K
                rows.append(r)
    agg = defaultdict(list)
    for r in rows:
        agg[(r["N"], round(r["rho_star"], 4))].append(r)
    hold = []
    for k, R in sorted(agg.items()):
        m = {tag: float(np.mean([r[tag]["miss_all_rate"] for r in R]))
             for tag in ("uniform", "shaped_oracle", "shaped_holdout")}
        hold.append({"N": k[0], "rho_star": k[1], "n": len(R), **{"miss_" + t: v for t, v in m.items()},
                     "gain_oracle_pct": 100.0 * (m["shaped_oracle"] - m["uniform"]) / m["uniform"],
                     "gain_holdout_pct": 100.0 * (m["shaped_holdout"] - m["uniform"]) / m["uniform"],
                     "miss_cert_total": int(sum(r["shaped_holdout"]["miss_cert"] for r in R)),
                     "n_cert_total": int(sum(r["shaped_holdout"]["n_cert"] for r in R))})
    out["holdout"] = {"rows": hold,
                      "note": "negative gain = shaping beats uniform; oracle fits K on the evaluation half, holdout fits on the other half",
                      "mean_gain_oracle_pct": float(np.mean([h["gain_oracle_pct"] for h in hold])),
                      "mean_gain_holdout_pct": float(np.mean([h["gain_holdout_pct"] for h in hold])),
                      "holdout_wins_cells": int(sum(1 for h in hold if h["gain_holdout_pct"] < 0)),
                      "cells": len(hold)}

    # ---- (ii) PER-DATASET -----------------------------------------------------------
    per = []
    for ds in ("CDnet2014", "LASIESTA", "BMC"):
        vs = [v for v in videos if v[0] == ds]
        for N in Ns:
            if len(vs) < N:
                continue
            for rho_star in budgets:
                acc = defaultdict(list)
                for sd in range(seeds):
                    rng = random.Random(SEED * 1000 + sd)
                    sub = rng.sample(vs, N)
                    streams = all_streams(sub, nframes, events, H)
                    Ku = max(2, math.ceil(N / rho_star))
                    for tag, K in (("uniform", [Ku] * N),
                                   ("shaped_harm", shaped_harmonic_windows(streams, rho_star)[0])):
                        e = eval_profile(streams, K, H, "harmonic")
                        if e is None:
                            continue
                        acc[tag].append(e)
                if not acc.get("uniform") or not acc.get("shaped_harm"):
                    continue
                mu = float(np.mean([e["miss_all_rate"] for e in acc["uniform"]]))
                ms = float(np.mean([e["miss_all_rate"] for e in acc["shaped_harm"]]))
                per.append({"dataset": ds, "n_videos": len(vs), "N": N, "rho_star": rho_star,
                            "miss_uniform": mu, "miss_shaped": ms,
                            "gain_pct": 100.0 * (ms - mu) / mu,
                            "miss_cert_total": int(sum(e["miss_cert"] for e in acc["shaped_harm"])),
                            "n_cert_total": int(sum(e["n_cert"] for e in acc["shaped_harm"]))})
    out["per_dataset"] = {"rows": per,
                          "duration_stats": {ds: {
                              "n_videos": sum(1 for v in videos if v[0] == ds),
                              "n_events": int(sum(len(events[v]) for v in videos if v[0] == ds)),
                              "median_duration": float(np.median(
                                  [d for v in videos if v[0] == ds for (_, d) in events[v]])),
                              "p90_duration": float(np.percentile(
                                  [d for v in videos if v[0] == ds for (_, d) in events[v]], 90)),
                              "mean_duration": float(np.mean(
                                  [d for v in videos if v[0] == ds for (_, d) in events[v]]))}
                              for ds in ("CDnet2014", "LASIESTA", "BMC")}}

    # ---- (iii) CERTIFIED-LATENCY CAP K_max ------------------------------------------
    cap_rows = []
    for N in Ns:
        for rho_star in budgets:
            for Kmax in (16, 32, 64):
                acc = []
                for sd in range(seeds):
                    rng = random.Random(SEED * 1000 + sd)
                    streams = build_streams(rng, videos, nframes, events, N, H)
                    best = None
                    for a in range(2, 17):
                        grid = [a << j for j in range(0, 8) if (a << j) <= Kmax]
                        if len(grid) < 2:
                            continue
                        K = shaped_windows(streams, rho_star, grid=grid)
                        o = shaping_objective(streams, K)
                        if best is None or o < best[0]:
                            best = (o, K)
                    if best is None:
                        continue
                    e = eval_profile(streams, best[1], H, "harmonic")
                    if e is None:
                        continue
                    acc.append(e)
                if acc:
                    cap_rows.append({"N": N, "rho_star": rho_star, "K_max": Kmax, "n": len(acc),
                                     "miss_all_rate": float(np.mean([e["miss_all_rate"] for e in acc])),
                                     "lat_max_cert": int(max(e["lat_max_cert"] for e in acc)),
                                     "miss_cert_total": int(sum(e["miss_cert"] for e in acc)),
                                     "n_cert_total": int(sum(e["n_cert"] for e in acc))})
    out["latency_cap"] = {"rows": cap_rows,
                          "note": "K_max caps the certified latency (Lemma 1 gives L <= K_i - 1) at the cost of a coarser shaping grid"}

    # ---- (iv) ROUND-ROBIN baseline (R2-6) -------------------------------------------
    rr_rows = []
    for N in Ns:
        for rho_star in budgets:
            acc_rr, acc_h = [], []
            for sd in range(seeds):
                rng = random.Random(SEED * 1000 + sd)
                streams = build_streams(rng, videos, nframes, events, N, H)
                Ku = max(2, math.ceil(N / rho_star))
                K = [Ku] * N
                acc_rr.append(eval_profile(streams, K, H, "rr"))
                e = eval_profile(streams, K, H, "harmonic")
                if e:
                    acc_h.append(e)
            rr_rows.append({"N": N, "rho_star": rho_star,
                            "rr_miss": float(np.mean([e["miss_all_rate"] for e in acc_rr])),
                            "rr_busy": float(np.mean([e["busy"] for e in acc_rr])),
                            "rr_violating": int(sum(e["violating_cameras"] for e in acc_rr)),
                            "harm_miss": float(np.mean([e["miss_all_rate"] for e in acc_h])) if acc_h else None,
                            "harm_busy": float(np.mean([e["busy"] for e in acc_h])) if acc_h else None,
                            "harm_violating": int(sum(e["violating_cameras"] for e in acc_h)) if acc_h else None})
    out["round_robin_baseline"] = {"rows": rr_rows,
                                   "note": "work-conserving proportional-share round robin: busy = 1 always, so it spends the full energy budget"}
    json.dump(out, open(os.path.join(RESULTS, "E8_sensitivity.json"), "w"), indent=1)
    return out


# --------------------------------------------------------------------------- figures
def make_figs2():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    # Embed text as Type 42 (TrueType) outlines, not the Type 3 bitmapped glyphs matplotlib
    # writes by default: Type 3 text in a figure makes the whole manuscript PDF report Type 3
    # fonts, which are not searchable and render blurry when zoomed.
    matplotlib.rcParams["pdf.fonttype"] = 42
    matplotlib.rcParams["ps.fonttype"] = 42
    plt.rcParams.update({"font.size": 9, "axes.titlesize": 9, "axes.labelsize": 9,
                         "xtick.labelsize": 8, "ytick.labelsize": 8, "legend.fontsize": 8})

    def save(fig, name):
        fig.tight_layout()
        fig.savefig(os.path.join(RESULTS, name + ".pdf"))
        fig.savefig(os.path.join(RESULTS, name + ".png"), dpi=200)
        plt.close(fig)

    # --- E1 (+ conservatism) : round-1 data, re-rendered as vector PDF --------
    p = os.path.join(RESULTS, "E1_density_sweep.json")
    q = os.path.join(RESULTS, "E1b_admission_conservatism.json")
    if os.path.exists(p) and os.path.exists(q):
        d, c = json.load(open(p)), json.load(open(q))
        labels = list(d["bins"].keys())
        x = np.arange(len(labels))
        short = [l.replace("(", "").replace("]", "").replace(",", "–") for l in labels]
        fig, axs = plt.subplots(1, 2, figsize=(7.0, 2.9))
        ex = [d["bins"][b]["exact_schedulable_frac"] or 0 for b in labels]
        ed = [d["bins"][b]["edf_ok_frac"] or 0 for b in labels]
        hm = [d["bins"][b]["harmonic_ok_frac"] or 0 for b in labels]
        wh = [d["bins"][b].get("wheel_ok_frac") or 0 for b in labels]
        w4 = 0.21
        axs[0].bar(x - 1.5 * w4, ex, w4, label="schedulable (exact search)")
        axs[0].bar(x - 0.5 * w4, wh, w4, label="constructive: divisor wheel")
        axs[0].bar(x + 0.5 * w4, hm, w4, label="constructive: single-base harmonic")
        axs[0].bar(x + 1.5 * w4, ed, w4, label="lazy EDF: no violation")
        axs[0].axvline(4.5, color="k", ls="--", lw=1)
        axs[0].text(4.6, 1.04, "5/6", fontsize=8)
        axs[0].set_ylim(0, 1.06)
        axs[0].set_yticks([0, 0.25, 0.5, 0.75, 1.0])
        axs[0].set_ylabel("fraction of random profiles")
        axs[0].set_title("schedulability vs density")
        cb = {r["bin"]: r for r in c["bins"]}
        axs[1].bar(x, [100 * (cb[b]["conservatism"] or 0) for b in labels], 0.6, color="C3")
        axs[1].set_ylabel("schedulable profiles refused (%)")
        axs[1].set_title("price of the O(1) density test")
        for ax in axs:
            ax.set_xticks(x)
            ax.set_xticklabels(short, rotation=40, ha="right", fontsize=7)
            ax.set_xlabel(r"density $\rho=\sum_i 1/K_i$")
        h, lb = axs[0].get_legend_handles_labels()
        fig.legend(h, lb, loc="lower center", ncol=2, fontsize=7, frameon=False,
                   bbox_to_anchor=(0.5, -0.06))
        fig.tight_layout()
        fig.savefig(os.path.join(RESULTS, "fig_E1_schedulability.pdf"), bbox_inches="tight")
        fig.savefig(os.path.join(RESULTS, "fig_E1_schedulability.png"), dpi=200,
                    bbox_inches="tight")
        plt.close(fig)

    # --- E2 : round-1 data, re-rendered as vector PDF --------------------------
    p = os.path.join(RESULTS, "E2_trace_frontier.json")
    if os.path.exists(p):
        d = json.load(open(p))
        fig, axs = plt.subplots(1, 2, figsize=(7.0, 2.9))
        for prof, mk, ls in (("uniform", "o", "-"), ("shaped_harm", "s", "--")):
            for N, col in ((4, "C0"), (6, "C1"), (8, "C2"), (12, "C3")):
                S = sorted([s for s in d["summary"] if s["profile"] == prof
                            and s["scheduler"] == "harmonic" and s["N"] == N],
                           key=lambda s: s["busy_mean"])
                if S:
                    axs[0].plot([s["busy_mean"] for s in S], [s["miss_all_rate_mean"] for s in S],
                                marker=mk, color=col, ls=ls, ms=4,
                                label=("uniform" if prof == "uniform" else "shaped") + f" N={N}")
        axs[0].axvline(5 / 6, color="k", ls=":", lw=1)
        axs[0].set_xlabel("busy fraction of the accelerator")
        axs[0].set_ylabel("uncertified miss rate")
        axs[0].set_title("budget shaping at equal energy")
        axs[0].legend(ncol=2, fontsize=6.5, framealpha=0.9)
        S = [s for s in d["summary"] if s["scheduler"] == "edf_lazy"]
        for prof, col, mk in (("uniform", "C0", "o"), ("shaped_harm", "C2", "s"),
                              ("shaped_int", "C3", "^")):
            P = [s for s in S if s["profile"] == prof]
            axs[1].scatter([s["rho_mean"] for s in P], [s["violating_runs"] / s["n"] for s in P],
                           c=col, marker=mk, s=18, label=prof)
        axs[1].axvline(5 / 6, color="k", ls=":", lw=1)
        axs[1].set_xlabel(r"realised density $\rho$")
        axs[1].set_ylabel("runs with a certificate violation")
        axs[1].set_title("lazy EDF breaks the certificate")
        axs[1].legend(framealpha=0.9)
        save(fig, "fig_E2_frontier")

    # --- E4 -------------------------------------------------------------------
    p = os.path.join(RESULTS, "E4_fleet_dimensioning.json")
    if os.path.exists(p):
        d = json.load(open(p))
        fig, axs = plt.subplots(1, 2, figsize=(7.0, 2.9))
        for ax, prof in zip(axs, ("uniform", "trace_heterogeneous")):
            R = [r for r in d["rows"] if r["profile"] == prof]
            Kt = sorted({r["K_target"] for r in R})
            w = 0.26
            for i, (meth, lab) in enumerate((("cor3_harmonic_ffd", "Cor. 3 harmonic+FFD"),
                                             ("ffd_5_6_heuristic", "FFD at 5/6 (heuristic)"),
                                             ("edf_fit_heuristic", "EDF-fit (heuristic)"))):
                y = [next(r["boxes"] for r in R if r["K_target"] == k and r["method"] == meth)
                     for k in Kt]
                ax.bar(np.arange(len(Kt)) + (i - 1) * w, y, w, label=lab)
            lb = [next(r["lower_bound_boxes"] for r in R if r["K_target"] == k) for k in Kt]
            ax.plot(np.arange(len(Kt)), lb, "k_", ms=18, label=r"lower bound $\lceil\rho\rceil$")
            ax.set_xticks(np.arange(len(Kt)))
            ax.set_xticklabels([str(k) for k in Kt])
            ax.set_xlabel(r"$K_{\rm target}$ (slots)")
            ax.set_ylabel("edge boxes for 121 cameras")
            ax.set_title(prof.replace("_", " "))
        axs[0].legend(loc="upper right", framealpha=0.9)
        save(fig, "fig_E4_dimensioning")

    # --- E5 -------------------------------------------------------------------
    p = os.path.join(RESULTS, "E5_churn_admission.json")
    if os.path.exists(p):
        d = json.load(open(p))
        fig, axs = plt.subplots(1, 2, figsize=(7.0, 2.9))
        pols = ["admit_then_edf", "density_5_6", "density_1_harmonic",
                "harmonic_residue_constructive"]
        labs = ["admit-then-EDF", "density test 5/6 (Cor. 2)", "density test 1, harmonic",
                "residue wheel (test + constructive schedule)"]
        lam = sorted({(s["lambda_in"], s["lambda_out"]) for s in d["summary"]})
        x = np.arange(len(lam))
        w = 0.20
        for i, (pol, lab) in enumerate(zip(pols, labs)):
            v = [next(s["violations_per_1k_slots"] for s in d["summary"]
                      if s["policy"] == pol and (s["lambda_in"], s["lambda_out"]) == L) for L in lam]
            rj = [100 * next(s["rejection_rate"] for s in d["summary"]
                             if s["policy"] == pol and (s["lambda_in"], s["lambda_out"]) == L) for L in lam]
            axs[0].bar(x + (i - 1.5) * w, v, w, label=lab)
            axs[1].bar(x + (i - 1.5) * w, rj, w, label=lab)
        for ax, yl in zip(axs, ["certificate violations / 1000 slots", "camera requests rejected (%)"]):
            ax.set_xticks(x)
            ax.set_xticklabels(["%.3f" % L[0] for L in lam])
            ax.set_xlabel(r"camera join rate $\lambda_{\rm in}$ (per slot)")
            ax.set_ylabel(yl)
        axs[0].set_ylim(0, 5.0)
        axs[0].legend(framealpha=0.95, loc="upper left", fontsize=6.5)
        axs[0].set_title("certificate violations under churn")
        axs[1].set_title("price paid: rejected admissions")
        save(fig, "fig_E5_churn")

    # --- E3 + E6 combined: "two edge realities" (round 3: merged, was Fig. 4 + Fig. 7) ---
    p3 = os.path.join(RESULTS, "E3_switch_cost.json")
    p6 = os.path.join(RESULTS, "E6_blackout.json")
    if os.path.exists(p3) and os.path.exists(p6):
        d3, d6 = json.load(open(p3)), json.load(open(p6))
        fig, axs = plt.subplots(1, 2, figsize=(7.0, 2.9))
        for sc, col, mk in ((0, "C0", "o"), (1, "C1", "s"), (2, "C2", "^"), (3, "C3", "v")):
            S = sorted([r for r in d3["summary"] if r["s"] == sc], key=lambda r: r["rho_eff"])
            axs[0].plot([r["rho_eff"] for r in S], [r["violating_runs"] / r["n"] for r in S],
                        marker=mk, color=col, ms=4, label=r"$s=%d$" % sc)
        axs[0].axvline(1.0, color="k", ls=":", lw=1)
        axs[0].set_xlabel(r"effective density $(1+s)\sum_i 1/K_i$")
        axs[0].set_ylabel("runs with a certificate violation")
        axs[0].set_title("(a) model-switch cost divides capacity")
        axs[0].legend(framealpha=0.9, title="switch cost")
        for l, mk in ((2, "o"), (4, "s"), (8, "^")):
            S = sorted([s for s in d6["summary"] if s["l"] == l and s["mode"] == "periodic"],
                       key=lambda s: s["K_avail"])
            axs[1].plot([s["K_avail"] for s in S], [s["violating_runs"] / s["n"] for s in S], mk,
                        ls="none", label=r"$\ell=%d$" % l, alpha=0.8)
        axs[1].axvline(6, color="k", ls="--", lw=1)
        axs[1].text(6.3, 0.55, r"$K''=N=6$", fontsize=8)
        axs[1].set_xlabel(r"available window $K''=K-B$ (slots)")
        axs[1].set_ylabel("runs with a certificate violation")
        axs[1].set_title("(b) escalation blackouts shrink the window")
        axs[1].legend(framealpha=0.9, title="escalation length")
        save(fig, "fig_E36_extensions")

    # --- E7 -------------------------------------------------------------------
    p = os.path.join(RESULTS, "E7_energy_mJ.json")
    if os.path.exists(p):
        d = json.load(open(p))
        fig, axs = plt.subplots(1, 2, figsize=(7.0, 2.9))
        for N, c in ((4, "C0"), (6, "C1"), (8, "C2"), (12, "C3")):
            R = sorted([r for r in d["rows"] if r["N"] == N and r["profile"] == "shaped_harm"],
                       key=lambda r: r["busy"])
            if not R:
                continue
            axs[0].plot([r["mJ_per_camera_frame_shared"] for r in R],
                        [r["miss_all_rate"] for r in R], "o-", color=c, label=f"N={N}")
            axs[1].plot([r["rho"] for r in R], [r["consolidation_gain"] for r in R], "s-", color=c,
                        label=f"N={N}")
        axs[0].set_xlabel("energy per camera-frame (mJ)")
        axs[0].set_ylabel("uncertified miss rate")
        axs[0].set_title("energy-miss frontier, absolute mJ")
        axs[1].set_xlabel(r"density $\rho$")
        axs[1].set_ylabel(r"consolidation gain (private / shared)")
        axs[1].set_title("one shared accelerator vs. N private ones")
        axs[0].legend(framealpha=0.9)
        save(fig, "fig_E7_energy")

    # --- E8 -------------------------------------------------------------------
    p = os.path.join(RESULTS, "E8_sensitivity.json")
    if os.path.exists(p):
        d = json.load(open(p))
        fig, axs = plt.subplots(1, 2, figsize=(7.0, 2.9))
        H = d["holdout"]["rows"]
        for N, c in ((6, "C1"), (8, "C2"), (12, "C3")):
            R = sorted([h for h in H if h["N"] == N], key=lambda h: h["rho_star"])
            if not R:
                continue
            axs[0].plot([r["rho_star"] for r in R], [r["gain_oracle_pct"] for r in R], "o-",
                        color=c, label=f"N={N} oracle")
            axs[0].plot([r["rho_star"] for r in R], [r["gain_holdout_pct"] for r in R], "s--",
                        color=c, label=f"N={N} hold-out")
        axs[0].axhline(0, color="k", lw=1)
        axs[0].set_xlabel(r"density budget $\rho^\star$")
        axs[0].set_ylabel("miss change vs uniform (%)")
        axs[0].set_title("shaping without an oracle")
        axs[0].legend(ncol=2, framealpha=0.9)
        P = d["per_dataset"]["rows"]
        dss = ["CDnet2014", "LASIESTA", "BMC"]
        x = np.arange(len(dss))
        w = 0.26
        for i, N in enumerate((6, 8, 12)):
            y = [float(np.mean([r["gain_pct"] for r in P if r["dataset"] == ds and r["N"] == N]))
                 if any(r["dataset"] == ds and r["N"] == N for r in P) else 0.0 for ds in dss]
            axs[1].bar(x + (i - 1) * w, y, w, label=f"N={N}")
        axs[1].axhline(0, color="k", lw=1)
        axs[1].set_xticks(x)
        axs[1].set_xticklabels(dss)
        axs[1].set_ylabel("miss change vs uniform (%)")
        axs[1].set_title("per dataset")
        axs[1].legend(framealpha=0.9)
        save(fig, "fig_E8_sensitivity")


# --------------------------------------------------------------------------- main
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--exp", default="all",
                    choices=["E1b", "E4", "E5", "E6", "E7", "E8", "figs", "all"])
    ap.add_argument("--quick", action="store_true")
    a = ap.parse_args()
    os.makedirs(RESULTS, exist_ok=True)
    random.seed(SEED)
    np.random.seed(SEED)
    videos, nframes, events, meta = load_corpus()
    print("corpus:", meta["n_videos"], "videos /", meta["n_events"], "events")
    t0 = time.time()
    if a.exp in ("E1b", "all"):
        o = run_E1b()
        print("E1b:", json.dumps(o["overall"]), f"[{time.time()-t0:.1f}s]")
    if a.exp in ("E4", "all"):
        o = run_E4(a.quick, videos, nframes, events)
        print("E4 rows:", len(o["rows"]), f"[{time.time()-t0:.1f}s]")
    if a.exp in ("E5", "all"):
        o = run_E5(a.quick, videos, nframes, events)
        print("E5 rows:", len(o["summary"]), f"[{time.time()-t0:.1f}s]")
    if a.exp in ("E6", "all"):
        o = run_E6(a.quick, videos, nframes, events)
        print("E6 prediction:", o["prediction_cells_correct"], "/", o["prediction_cells"],
              f"[{time.time()-t0:.1f}s]")
    if a.exp in ("E7", "all"):
        o = run_E7()
        print("E7 gain:", round(o["gain_min"], 3), "-", round(o["gain_max"], 3),
              f"[{time.time()-t0:.1f}s]")
    if a.exp in ("E8", "all"):
        o = run_E8(a.quick, videos, nframes, events)
        print("E8 holdout mean gain %:", round(o["holdout"]["mean_gain_holdout_pct"], 2),
              "oracle:", round(o["holdout"]["mean_gain_oracle_pct"], 2), f"[{time.time()-t0:.1f}s]")
    if a.exp in ("figs", "all"):
        make_figs2()
        print("figs written", f"[{time.time()-t0:.1f}s]")


if __name__ == "__main__":
    main()
